services:
  - type: web
    name: argx-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py

databases:
  - name: arg-db
    databaseName: argdb
    user: arg_user
